name=QMC5883L
version=1.0.0
author=Alexander Voronkov
maintainer=Alexander Voronkov
sentence=QMC5883L magnetometer library for Arduino
paragraph=Lightweight library for working with the QMC5883L 3-axis magnetometer via I2C. Supports configuration, status monitoring and magnetic field measurement.
category=Sensors
url=https://github.com/VipNooob/qmc5883l_library
architectures=*
depends=
